arch: amd64
os: linux
dist: focal

language: node_js
node_js:
  - "node"

addons:
  apt:
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  # - ng lint
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - ng build --prod

before_deploy:
  # Deploy from library build folder
  - cd ${TRAVIS_BUILD_DIR}/dist/rahimalizada/ngx-common

deploy:
  provider: npm
  email: "rahim.alizada@gmail.com"
  api_token:
    # Generated per repository
    secure: "omxrCNuSXuyMJtLvvw/7y8KA/sPr9m7merSHs8xsISUCiB7i5RibSbms+G9ZXMzDvKp4yCgEmGvxcjLNOdUFCWmmhrcaqh7ZjqgOmg2d6YCwiilYlKT381qqZxJEkV3EEQfy/YO67EoU7GJSpaBbAgqTA8gghyZjld7PJRaIPGvzVyB1+JxHLrQC0rFoHgIu1Jrq5vCias196Dvr8ipnPQuCEZE+lq9htfZ1z0HucqB+NzcvvyxlbK0Cphs7tiWeW4B0h3W+wkQSCu+tj2O2GXwjNFVMFQmBF+eAbyds5GKhZL5LDGYzjjoOZiwKWizVFgrJPqVfG0SzIROciCv9EbkVXNl1TursxLi6o/VFd6jeUTZYPqdatXegXS2rP6omI7GYZLPKtICJ1iK3pATuZz6QtVFRtLXpbRUny0hctZIKykkUq2ZSI7CCvtOmiiPtjYVph0zVXddKmO8mgQHvfO7/Uo0HdKICjbnjrsvXw5EkmWK9t9nbAszoEqR4TcnIOQK9uLPZ15ZyG7pYomtJPanBurndr4cgN4fil6qJumeA/n3J+dymWkQaIKE1yrOBHr7LlO67+YIttPvuM9ndSFSTIPInJysTCZm3qEW2RgegyszvkZ+xAIcwYav/pONDtR0wuXlZ3lRD71e8Z4xd4hCe05opwFPA4e0AcCyLrMw="
  on:
    tags: true
  skip_cleanup: true
